/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        extend: {
            animation: {
                example: "example 10s ease-in-out infinite running",
            },
            aspectRatio: {
                carousel: "10 / 12",
                carousel_cat: "10/11.7",
                carousel_lg: "10/14",
                city: "3/2",
                flower: "3/1",
            },
            backgroundImage: {
                arrow: "url('Assets/Img/arrow.svg')",
                small_linear: "linear-gradient(0deg, #9C96A2, #3A383C)",
                card_linear: "linear-gradient(0deg, #8792C8, #44539D, #1E1338)",
                linear: "linear-gradient(180deg, #132A9B, #070E35)",
                radial: "radial-gradient(at center, #FF8B8B, #FC0303)",
                section_radial: "radial-gradient(at center, #FCFCFB, #F2CBCB)",
                box_linear: "linear-gradient(0deg, #6880FF, #3F4D99)",
                city_img: "url('Assets/Img/city.png')",
                rock: "url('Assets/Img/rock.png')",
                beach: "url('Assets/Img/beach.png')",
                teammember: "url('Assets/Img/team_membercard.png')",
                street: "url('Assets/Img/street.png')",
            },
            borderRadius: {
                "1/2": "50%",
                12: "12px",
            },
            colors: {
                primary: "#F2EEE8",
                main_red: "#FF3400",
                main_orange: "#FF7504",
                main_green: "#81FA10",
                header_button: "#FF0707",
                section_at: "#808080",
                section_best: "#FF3400",
                section_maincard: "#FCFCFB",
                section_websites: "#FF7504",
                section_on: "#423F3F",
                section_planet: "#81FA10",
                circle: "#FF0000",
                card: "#6C6E98",
                city: "#5F75E9",
                ghost: "#4E5DA3",
                letter: "#3E3B37",
                box_color: "#7C7A7A",
                orange_100: "#EAE8E3",
                orange_200: "#FCE5D5",
                purple_700: "#913DEB",
                cyan_100: "#E3FEFF",
                cyan_600: "#08B6BF",
                gray_300: "#6A6C73",
                gray_400: "#B4B4B4",
                gray_500: "#F4F1EC",
                gray_600: "#E3DED5",
                gray_700: "#9C9898",
                gray_900: "#2D2A3C",
                gray_800: "#040404",
                red_700: "#CE0808",
                red_800: "#FF0606",
                slate_50: "#D3D3D3",
                slate_100: "#FFFEFD",
                slate_200: "#737272",
                slate_300: "#7E7C7C",
                slate_400: "#BBBABA",
                slate_800: "#414040",
                zinc_950: "#090909",
            },
            fontFamily: {
                jersey: ['"Jersey 20"', "sans-serif"],
                inter: ["Inter", "sans-serif"],
                instrument: ['"Instrument Serif"', "sans-serif"],
                istok: ["Istok Web", "sans-serif"],
                junge: ["Junge", "serif"],
                finger: ['"Finger Paint"', "cursive"],
            },
            fontSize: {
                40: "40px",
                64: "64px",
                "7xl": "82px",
                86: "86px",
                90: "90px",
                "10xl": "150px",
                200: "200px",
                300: "300px",
            },
            gap: {
                18: "72px",
            },
            height: {
                "32vw": "32vw",
            },
            keyframes: {
                example: {
                    "0%": {
                        right: "-100%",
                    },
                    "100%": {
                        right: "100%",
                    },
                },
            },
            letterSpacing: {
                tightest: "-0.04em",
            },
            lineHeight: {
                20: "20px",
                25: "25px",
                40: "40px",
                64: "64px",
                75: "75px",
                94: "94px",
                100: "100px",
                132: "132px",
                150: "150px",
            },
            padding: {
                13: "52px",
                39: "156Px",
            },
            screens: {
                "3xs": "320px",
                xxs: "375px",
                xs: "425px",
                b_xl: "1360px", // between xl and xxl
                "3xl": "1680px",
                b_3xl: "1900px", // between 3xl and 4xl
            },
            spacing: {
                carouselLeftArrow: "76%",
                carouselRightArrow: "82%",
            },
            width: {
                30: "120px",
                62.5: "250px",
                "23vw": "23vw",
                "24vw": "24vw",
                "43vw": "43vw",
                "44vw": "44vw",
            },
        },
    },
    plugins: [
        function ({ addUtilities }) {
            addUtilities({
                ".animation-paused": { "animation-play-state": "paused" },
                ".animation-running": { "animation-play-state": "running" },
            });
        },
    ],
};
